In [4]:
import pandas as pd

In [5]:

csv_path1 = "data/input/akc-data-latest.csv"
akc_df = pd.read_csv(csv_path1)
akc_df.head()

,breed,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,grooming_frequency_value,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category
0,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148,22.86,29.21,3.175147,4.535924,12.0,15.0,...,0.6,2-3 Times a Week Brushing,0.6,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing
1,Afghan Hound,"The Afghan Hound is an ancient breed, his whol...","Dignified, Profoundly Loyal, Aristocratic",113,63.50,68.58,22.679619,27.215542,12.0,15.0,...,0.8,Daily Brushing,0.2,Infrequent,0.8,Energetic,0.2,May be Stubborn,0.2,Aloof/Wary
2,Airedale Terrier,The Airedale Terrier is the largest of all ter...,"Friendly, Clever, Courageous",60,58.42,58.42,22.679619,31.751466,11.0,14.0,...,0.6,2-3 Times a Week Brushing,0.4,Occasional,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly
3,Akita,"Akitas are burly, heavy-boned spitz-type dogs ...","Courageous, Dignified, Profoundly Loyal",47,60.96,71.12,31.751466,58.967008,10.0,13.0,...,0.8,Daily Brushing,0.6,Seasonal,0.8,Energetic,1.0,Eager to Please,0.6,Alert/Responsive
4,Alaskan Malamute,The Alaskan Malamute stands 23 to 25 inches at...,"Affectionate, Loyal, Playful",58,58.42,63.50,34.019428,38.555351,10.0,14.0,...,0.6,2-3 Times a Week Brushing,0.6,Seasonal,0.8,Energetic,0.4,Independent,0.8,Friendly

In [6]:

csv_path2 = "data/input/kaggle_breeds_unique.csv"
kaggle_df = pd.read_csv(csv_path2)
kaggle_df.head()

             kbreed
0       boston_bull
1             dingo
2          pekinese
3          bluetick
4  golden_retriever

In [7]:
# breed replace spaces with _

akc_df['akc_breed'] = akc_df['breed']

akc_df['akc_breed'] = akc_df['akc_breed'].str.replace(' ', '_', regex=False)
akc_df.head()

kaggle_df['akc_breed'] = kaggle_df['kbreed']

kaggle_df['akc_breed'] = kaggle_df['akc_breed'].str.replace(' ', '_', regex=False)
kaggle_df.head()

             kbreed         akc_breed
0       boston_bull       boston_bull
1             dingo             dingo
2          pekinese          pekinese
3          bluetick          bluetick
4  golden_retriever  golden_retriever

In [8]:
# breed all lowercase
akc_df['akc_breed'] = akc_df['akc_breed'].str.lower()
akc_df.head()

kaggle_df['akc_breed'] = kaggle_df['akc_breed'].str.lower()
kaggle_df.head()

             kbreed         akc_breed
0       boston_bull       boston_bull
1             dingo             dingo
2          pekinese          pekinese
3          bluetick          bluetick
4  golden_retriever  golden_retriever

In [9]:
# outer join to see all akc with matching kaggle

joined_data = akc_df.merge(kaggle_df, on='akc_breed', how='outer')
joined_data.head()

,breed,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category,akc_breed,kbreed
0,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148,22.86,29.21,3.175147,4.535924,12.0,15.0,...,0.6,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing,affenpinscher,affenpinscher
1,Afghan Hound,"The Afghan Hound is an ancient breed, his whol...","Dignified, Profoundly Loyal, Aristocratic",113,63.50,68.58,22.679619,27.215542,12.0,15.0,...,0.2,Infrequent,0.8,Energetic,0.2,May be Stubborn,0.2,Aloof/Wary,afghan_hound,afghan_hound
2,Airedale Terrier,The Airedale Terrier is the largest of all ter...,"Friendly, Clever, Courageous",60,58.42,58.42,22.679619,31.751466,11.0,14.0,...,0.4,Occasional,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly,airedale_terrier,NaN
3,Akita,"Akitas are burly, heavy-boned spitz-type dogs ...","Courageous, Dignified, Profoundly Loyal",47,60.96,71.12,31.751466,58.967008,10.0,13.0,...,0.6,Seasonal,0.8,Energetic,1.0,Eager to Please,0.6,Alert/Responsive,akita,NaN
4,Alaskan Malamute,The Alaskan Malamute stands 23 to 25 inches at...,"Affectionate, Loyal, Playful",58,58.42,63.50,34.019428,38.555351,10.0,14.0,...,0.6,Seasonal,0.8,Energetic,0.4,Independent,0.8,Friendly,alaskan_malamute,NaN

In [10]:
# export to csv for manual review of non-matches
joined_data.to_csv ('data/output/joined_breeds.csv', encoding='utf-8', index=False)

In [11]:
# read updated kaggle unique breeds list
csv_path3= "data/input/updates_kbreed.csv"
kupdated_df = pd.read_csv(csv_path3)
kupdated_df.head()

                         breed                    akc_breed
0            yorkshire_terrier            yorkshire_terrier
1      wire-haired_fox_terrier             wire_fox_terrier
2                      whippet                      whippet
3  west_highland_white_terrier  west_highland_white_terrier
4       welsh_springer_spaniel       welsh_springer_spaniel

In [12]:
# checking cleaning
joined_data2 = akc_df.merge(kupdated_df, on='akc_breed', how='outer')
joined_data2.head()

,breed_x,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category,akc_breed,breed_y
0,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148,22.86,29.21,3.175147,4.535924,12.0,15.0,...,0.6,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing,affenpinscher,affenpinscher
1,Afghan Hound,"The Afghan Hound is an ancient breed, his whol...","Dignified, Profoundly Loyal, Aristocratic",113,63.50,68.58,22.679619,27.215542,12.0,15.0,...,0.2,Infrequent,0.8,Energetic,0.2,May be Stubborn,0.2,Aloof/Wary,afghan_hound,afghan_hound
2,Airedale Terrier,The Airedale Terrier is the largest of all ter...,"Friendly, Clever, Courageous",60,58.42,58.42,22.679619,31.751466,11.0,14.0,...,0.4,Occasional,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly,airedale_terrier,airedale
3,Akita,"Akitas are burly, heavy-boned spitz-type dogs ...","Courageous, Dignified, Profoundly Loyal",47,60.96,71.12,31.751466,58.967008,10.0,13.0,...,0.6,Seasonal,0.8,Energetic,1.0,Eager to Please,0.6,Alert/Responsive,akita,NaN
4,Alaskan Malamute,The Alaskan Malamute stands 23 to 25 inches at...,"Affectionate, Loyal, Playful",58,58.42,63.50,34.019428,38.555351,10.0,14.0,...,0.6,Seasonal,0.8,Energetic,0.4,Independent,0.8,Friendly,alaskan_malamute,malamute

In [13]:
# exporting to get list to add to kaggle
joined_data2.to_csv ('data/output/joined_breeds_clean.csv', index=False)

In [14]:
# export

In [15]:
#read full kaggle labels file
csv_path4= "data/input/labels.csv"
klabels_df = pd.read_csv(csv_path4)
klabels_df.head()

                                 id             breed
0  000bec180eb18c7604dcecc8fe0dba07       boston_bull
1  001513dfcb2ffafc82cccf4d8bbaba97             dingo
2  001cdf01b096e06d78e9e5112d419397          pekinese
3  00214f311d5d2247d5dfe4fe24b2303d          bluetick
4  0021f9ceb3235effd7fcde7f7538ed62  golden_retriever

In [16]:
# join with updated kaggle uniques to add column for akc labels
joined_data3 = kupdated_df.merge(klabels_df, on='breed', how='outer')
joined_data3.head()

               breed          akc_breed                                id
0  yorkshire_terrier  yorkshire_terrier  07bbf36ce2c7407751219804b3d187ec
1  yorkshire_terrier  yorkshire_terrier  083820e6dda52da4c0f200ac36f582dc
2  yorkshire_terrier  yorkshire_terrier  0cb1bf12ae0fd5f681ae579c2a28ccd8
3  yorkshire_terrier  yorkshire_terrier  0f976e55b3634296183b2b1c051d5bda
4  yorkshire_terrier  yorkshire_terrier  0fa302727af44e7ad8033825cea98d7c

In [17]:
# export updated labels file for image model

joined_data3.to_csv ('data/output/labels_with_akc_names.csv', index=False)

In [18]:
# export akc with matching breed name
akc_df.to_csv ('data/output/akc_data_with_akc_names.csv', index=False)

In [19]:
#read updated akc file
csv_path5= "data/input/akc_data_cleaned.csv"
akc_updated_df = pd.read_csv(csv_path5)
akc_updated_df.head()

,breed,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,grooming_frequency_category,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category,akc_breed
0,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148,10,12,7,12,12,15,...,2-3 Times a Week Brushing,0.6,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing,affenpinscher
1,Afghan Hound,"The Afghan Hound is an ancient breed, his whol...","Dignified, Profoundly Loyal, Aristocratic",113,25,27,50,60,12,15,...,Daily Brushing,0.2,Infrequent,0.8,Energetic,0.2,May be Stubborn,0.2,Aloof/Wary,afghan_hound
2,Airedale Terrier,The Airedale Terrier is the largest of all ter...,"Friendly, Clever, Courageous",60,21,23,44,50,11,14,...,2-3 Times a Week Brushing,0.4,Occasional,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly,airedale_terrier
3,Akita,"Akitas are burly, heavy-boned spitz-type dogs ...","Courageous, Dignified, Profoundly Loyal",47,24,28,70,130,10,13,...,Daily Brushing,0.6,Seasonal,0.8,Energetic,1.0,Eager to Please,0.6,Alert/Responsive,akita
4,Alaskan Malamute,The Alaskan Malamute stands 23 to 25 inches at...,"Affectionate, Loyal, Playful",58,23,25,75,85,10,14,...,2-3 Times a Week Brushing,0.6,Seasonal,0.8,Energetic,0.4,Independent,0.8,Friendly,alaskan_malamute

In [20]:
# joining clean akc to clean kaggle ids for data by image id
joined_data4 = akc_updated_df.merge(kupdated_df, on='akc_breed', how='outer')
joined_data4.head()

,breed_x,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category,akc_breed,breed_y,id
0,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148.0,10.0,12.0,7.0,12.0,12.0,15.0,...,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing,affenpinscher,affenpinscher,00ca18751837cd6a22813f8e221f7819
1,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148.0,10.0,12.0,7.0,12.0,12.0,15.0,...,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing,affenpinscher,affenpinscher,01268f0007876a692907bda89468184c
2,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148.0,10.0,12.0,7.0,12.0,12.0,15.0,...,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing,affenpinscher,affenpinscher,0162107acd8f2588c0944b791d61bb0c
3,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148.0,10.0,12.0,7.0,12.0,12.0,15.0,...,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing,affenpinscher,affenpinscher,040fef64640b89c53f161b6c5215b78b
4,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148.0,10.0,12.0,7.0,12.0,12.0,15.0,...,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing,affenpinscher,affenpinscher,0484a6cc686a07e1edacd0fb44b1d965

In [21]:
# joining clean akc to clean kaggle names for unique breeds
joined_data5 = akc_updated_df.merge(kupdated_df, on='akc_breed', how='outer')
joined_data5.head()

,breed_x,description,temperament,popularity,min_height,max_height,min_weight,max_weight,min_expectancy,max_expectancy,...,shedding_value,shedding_category,energy_level_value,energy_level_category,trainability_value,trainability_category,demeanor_value,demeanor_category,akc_breed,breed_y
0,Affenpinscher,The Affen’s apish look has been described many...,"Confident, Famously Funny, Fearless",148.0,10.0,12.0,7.0,12.0,12.0,15.0,...,0.6,Seasonal,0.6,Regular Exercise,0.8,Easy Training,1.0,Outgoing,affenpinscher,affenpinscher
1,Afghan Hound,"The Afghan Hound is an ancient breed, his whol...","Dignified, Profoundly Loyal, Aristocratic",113.0,25.0,27.0,50.0,60.0,12.0,15.0,...,0.2,Infrequent,0.8,Energetic,0.2,May be Stubborn,0.2,Aloof/Wary,afghan_hound,afghan_hound
2,Airedale Terrier,The Airedale Terrier is the largest of all ter...,"Friendly, Clever, Courageous",60.0,21.0,23.0,44.0,50.0,11.0,14.0,...,0.4,Occasional,0.6,Regular Exercise,1.0,Eager to Please,0.8,Friendly,airedale_terrier,airedale
3,Akita,"Akitas are burly, heavy-boned spitz-type dogs ...","Courageous, Dignified, Profoundly Loyal",47.0,24.0,28.0,70.0,130.0,10.0,13.0,...,0.6,Seasonal,0.8,Energetic,1.0,Eager to Please,0.6,Alert/Responsive,akita,NaN
4,Alaskan Malamute,The Alaskan Malamute stands 23 to 25 inches at...,"Affectionate, Loyal, Playful",58.0,23.0,25.0,75.0,85.0,10.0,14.0,...,0.6,Seasonal,0.8,Energetic,0.4,Independent,0.8,Friendly,alaskan_malamute,malamute

In [22]:
# export final cleaned akc table with kaggle breed
joined_data5.to_csv ('data/output/final_akc_data_with_kaggle_breeds.csv', index=False)